version: '3.8'

services:
  post:
    build:
      context: ./Post
      dockerfile: Dockerfile
    ports:
      - "51148:51148"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mongo
    networks:
      - mynetwork
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

networks:
  mynetwork:

volumes:
  mongodb_data:
